#!/usr/bin/env pythonNone
# -*- coding: utf-8 -*-
#
# Copyright (c) 2018, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2018, Annika Ofenloch (DLR RY-AVS)

---
  # -------------------------------------------------------------------
  # Execute models local or remote
  # -------------------------------------------------------------------
- name: Run configuration server on the host
  command: "{{ remote_home_path }}/models/configuration_server/build/bin/configuration_server --config-file {{ remote_home_path }}/hosts-configs/{{ hosts_config_filepath | basename }}"
  async: 1000
  poll: 0
  changed_when: False

- name: Run models on the hosts
  shell: "{{ remote_home_path }}/models/{{ item.0 | basename }}/build/bin/* -n {{ item.1 }}"
  async: 1000
  poll: 0
  loop: "{{ model_paths|zip(model_ids)|list }}"
  when:
    - 'not "simulation_model" in item.1'
    - 'not "configuration_server" in item.1'
    - 'not "logger" in item.1'
  changed_when: False

- name: Run simulation model on the host
  shell: "{{ remote_home_path }}/models/simulation_model/build/bin/simulation_model --load-config {{ remote_home_path }}/configurations/{{ config_path | basename }}/"
  async: 1000
  poll: 0
  changed_when: False

- name: Run logger model locally
  shell: "{{ remote_home_path }}/models/logger/build/bin/logger --log-files-path {{ remote_home_path }}/logs/"
  changed_when: False
  # -------------------------------------------------------------------