---
- name: Check if folders exists
  file: path="{{ item }}" state=directory
  with_items: 
  - "../models"
  - "../configurations"
  - "../fraser"
  changed_when: False
  
- name: Check if resource folders exists
  file: path="../models/{{ item }}/resources/idl" state=directory
  with_items: "{{ allmodels }}"
  changed_when: False
  
- name: Check if build folders exists
  file: path="../models/{{ item }}/build/dependencies/idl" state=directory
  with_items: "{{ allmodels }}"
  changed_when: False
  
- name: Dissolve IDL dependencies between the models
  copy:
    src: "../models/{{item.1}}/resources/idl"
    dest: "../models/{{item.0.name}}/build/dependencies/"
  with_subelements:
    - "{{ dependencies }}"
    - depends