---
- name: Check if folders exists
  file: path="{{ item }}" state=directory
  loop:
    - "../models"
    - "../configurations"
    - "../fraser"
    - "../ansible/inventory"
    - "../ansible/inventory/group_vars/all"
  changed_when: False

- name: Build hosts file
  command: python3.6 ../fraser/scripts/hostsGenerator.py -f ../models/configuration_server/configuration/models-config.xml -d ../ansible/

- name: Build variables file
  command: python3.6 ../fraser/scripts/modelsVarsGenerator.py -f ../models/configuration_server/configuration/models-config.xml -d ../ansible/
    
- name: Include main.yml file in group_vars/all (includes global variables)
  include_vars:
   file: "../ansible/inventory/group_vars/all/main.yml"

- name: Check if resource/idl folders exists
  file: path="../models/{{ item.name }}/resources/idl" state=directory
  loop: "{{ models }}"
  when: item.name != "configuration_server"
  changed_when: False
 
- name: Dissolve IDL dependencies between the models
  copy:
    src: "../models/{{item.1}}/resources/idl/"
    dest: "../models/{{item.0.name}}/resources/idl"
  with_subelements:
    - "{{ models }}"
    - depends
    
- name: Copy default event IDL C++ header to the models
  copy:
    src: "../resources/idl/event.fbs"
    dest: "../models/{{ item.name }}/resources/idl/"
  loop: "{{ models }}"
  when: item.name != "configuration_server"