---
- name: Ping host machines
  ping:
  register: hostsstable
  
- name: Print it was a success
  command: echo "Yeah"
  when: hostsstable|success
  changed_when: False

- name: Copy model directory to the remote hosts
  #become: True
  copy:
    src: ../models/{{ item }}
    dest: /tmp/simulation/models
  with_items: "{{ models }}"

- name: Run models on the hosts
  become: true
  shell: ./tmp/simulation/models/{{ item }}/build/bin/{{ item }}
  async: 1
  poll: 0
  with_items: "{{ models }}"
  register: result

- debug: var=result
