#!/usr/bin/env pythonNone
# -*- coding: utf-8 -*-
#
# Copyright (c) 2017-2018, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2017-2018, Annika Ofenloch (DLR RY-AVS)

---
  # -------------------------------------------------------------------
  # Copy files to remote hosts
  # -------------------------------------------------------------------
- name: Copy hosts configuration file to the remote hosts for the configuration server
  copy:
    src: "{{ hosts_config_filepath }}"
    dest: "{{ remote_home_path }}/hosts-configs/"

- name: Copy model directory to the remote hosts
  copy:
    src: "{{ item }}"
    dest: "{{ remote_home_path }}/models"
  loop: "{{ model_paths }}"

- name: Check if folders exists
  file: path="{{ item }}" state=directory
  loop:
    - "{{ remote_home_path }}/configurations/{{ config_path | basename }}"
    - "{{ remote_home_path }}/logs"

- name: Copy configuration file to remote hosts
  copy:
    src: ../configurations/{{ config_path | basename }}/{{ item }}.config
    dest: "{{ remote_home_path }}/configurations/{{ config_path | basename }}/"
  loop: "{{ model_ids }}"
  when: 'not "configuration_server" in item'

- name: Fix 'tmp-folder' permission
  file: path=tmp_simulation owner={{ lookup('env', 'USER') }} mode=0775 state=directory recurse=yes
  # -------------------------------------------------------------------