---
  # ---------------------------------------------------------
  # Install ZeroMQ
  # ---------------------------------------------------------
- name: install build-essential package
  apt: name=build-essential update_cache=no state=present

- name: Download ZeroMQ
  get_url: url={{ zeromq_download_url }} dest=/tmp/zeromq.zip

- name: Unarchive ZeroMQ tarball
  unarchive: >
    copy=no
    src=/tmp/zeromq.zip
    dest=/tmp/

- name: Configure ZeroMQ
  shell: ./configure --prefix={{ zeromq_prefix }} chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Build ZeroMQ
  shell: make chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Install ZeroMQ
  shell: make install chdir=/tmp/zeromq-{{ zeromq_version }}

- name: Remove ZeroMQ tarball
  file: path=/tmp/zeromq.zip state=absent

  # ---------------------------------------------------------
  # Install Git
  # ---------------------------------------------------------
- name: Install Git
  apt:
    name: git
    state: present
  register: installed_git

  # ---------------------------------------------------------
  # Install Flatbuffers
  # ---------------------------------------------------------
- name: Read-write checkout from Gitlab
  git: repo="https://github.com/google/flatbuffers.git"
       dest=/tmp/flatbuffers
  when: 
    - installed_git is success   

- name: Create Makefile for Flatbuffers
  shell: cmake -G "Unix Makefiles" chdir=/tmp/flatbuffers
  
- name: Build Flatbuffers
  shell: make chdir=/tmp/flatbuffers
  
- name: Run Tests of Flatbuffers
  shell: ./flattests chdir=/tmp/flatbuffers 