  # -----------------------------------------------------------------------
  # Update inventory file and the group variables
  # -----------------------------------------------------------------------
- name: Check if folders exists
  file: path="{{ item }}" state=directory
  loop:
    - "../ansible/inventory"
    - "../ansible/inventory/group_vars/all"
    
  # Create hosts file (inventory file)
- name: Build hosts file
  command: python3 ../fraser/scripts/hostsGenerator.py -f {{ hosts_config_filepath }} -d ../ansible/
  changed_when: False
- meta: refresh_inventory

  # Define global variables
- name: Build variables file
  command: python3 ../fraser/scripts/modelsVarsGenerator.py -f {{ hosts_config_filepath }} -d ../ansible/
  changed_when: False

- name: Include main.yml file in group_vars/all (includes global variables)
  include_vars:
   file: "../ansible/inventory/group_vars/all/main.yml"