- hosts: localhost
  become: True
  gather_facts: no
  vars: 
    - ansible_python_interpreter: /usr/bin/python3
    - zeromq_version: 4.2.3
    - zeromq_download_url: https://github.com/zeromq/libzmq/releases/download/v4.2.3/zeromq-4.2.3.tar.gz
    - zeromq_prefix: /usr/local   
  roles:
    - { role: configure, tags: configure }