---
- hosts: localhost
  gather_facts: no
  roles: 
    - { role: initialisation, tags: initialisation }

- hosts: localhost
  gather_facts: no
  roles: 
    - { role: build, tags: build }

- hosts: all:!localhost
  gather_facts: no
  vars:
    - config: config_0
  roles:
    - { role: deployment, tags: deployment }