---
- hosts: localhost
  gather_facts: no
  tasks:


- hosts: localhost
  gather_facts: no
  roles: 
    - initialisation

- hosts: localhost
  gather_facts: no
  roles: 
    - build

- hosts: all | !localhost
#  gather_facts: no
  roles:
    - deployment