---
- hosts: localhost
  gather_facts: no
  roles: 
    - { role: initialisation, tags: initialisation }

- hosts: localhost
  become: True
  gather_facts: no
  vars: 
    - ansible_python_interpreter: /usr/bin/python3
    - zeromq_version: 4.2.3
    - zeromq_download_url: https://github.com/zeromq/libzmq/releases/download/v4.2.3/zeromq-4.2.3.tar.gz
    - zeromq_prefix: /usr/local   
  roles:
    - { role: configure, tags: configure }

- hosts: localhost
  gather_facts: no
  roles: 
    - { role: build, tags: build }
    
- hosts: localhost
  gather_facts: no
  roles: 
    - { role: default-configs, tags: default-configs }
  
- hosts: all:!localhost
  gather_facts: no
  vars:
    - config: config_0
  roles:
    - { role: deployment, tags: deployment }